import type {TVSCreditEMIScene} from './types';

export const TVS_CREDIT_EMI_SCENES: TVSCreditEMIScene[] = [
  {
    kind: 'intro',
    eyebrow: 'Important Update',
    title: 'Hello {{customerName}}',
    subtitle: 'Regarding your {{productType}} account from {{clientName}}. An EMI amount of ₹{{tos}} is pending on account {{lan}}.',
    relativeDuration: { en: 0.286, hi: 0.265 },
  },
  {
    kind: 'text-only',
    method: 1,
    eyebrow: 'Method 1',
    title: 'Payment Link',
    subtitle: 'A secure link has been sent to you on WhatsApp and SMS.',
    relativeDuration: { en: 0.043, hi: 0.050 },
  },
  {
    kind: 'fullscreen-image',
    method: 1,
    image: 'paynow_whatsapp.png',
    caption: 'Click the "Pay Now" button on WhatsApp',
    relativeDuration: { en: 0.055, hi: 0.056 },
  },
  {
    kind: 'fullscreen-image',
    method: 1,
    image: 'link_sms.png',
    caption: 'Or click the link shared via SMS',
    relativeDuration: { en: 0.059, hi: 0.075 },
  },
  {
    kind: 'text-only',
    method: 2,
    eyebrow: 'Method 2',
    title: 'UPI / Payment Apps',
    subtitle: 'Pay conveniently using PhonePe, Google Pay, or any UPI app.',
    relativeDuration: { en: 0.055, hi: 0.057 },
  },
  {
    kind: 'fullscreen-image',
    method: 2,
    image: 'upi_app.png',
    caption: 'Open PhonePe or Google Pay',
    relativeDuration: { en: 0.070, hi: 0.086 },
  },
  {
    kind: 'fullscreen-image',
    method: 2,
    image: 'open_app_search.png',
    caption: 'Go to Repayment and search for payment option',
    relativeDuration: { en: 0.070, hi: 0.087 },
  },
  {
    kind: 'fullscreen-image',
    method: 2,
    image: 'enter_lan.png',
    caption: 'Enter LAN and complete payment using UPI PIN',
    relativeDuration: { en: 0.047, hi: 0.052 },
  },
  {
    kind: 'fullscreen-image',
    method: 2,
    image: 'payment_success.png',
    caption: 'Wait for successful payment confirmation',
    relativeDuration: { en: 0.051, hi: 0.046 },
  },
  {
    kind: 'text-only',
    method: 3,
    eyebrow: 'Method 3',
    title: 'EMI Collection Shop',
    subtitle: 'Visit your nearest EMI Collection Shop to deposit your EMI amount.',
    relativeDuration: { en: 0.058, hi: 0.055 },
  },
  {
    kind: 'fullscreen-image',
    method: 3,
    image: 'shop_visit.png',
    caption: 'Visit nearest EMI Collection Shop to deposit cash',
    relativeDuration: { en: 0.058, hi: 0.056 },
  },
  {
    kind: 'final',
    eyebrow: 'Final Reminder',
    title: 'Pay Today',
    subtitle: 'Contact {{contactDetails}} immediately to discuss options and avoid charges.',
    relativeDuration: { en: 0.149, hi: 0.115 },
  },
];
